name: cq-picsearcher-bot 镜像构建
on:
  repository_dispatch:
    types: [cq-picsearcher-bot]
  workflow_dispatch:

env:
  VERSION: ${{ github.event.client_payload.version }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone
        run: git clone https://github.com/Tsuk1ko/cq-picsearcher-bot ./cq-picsearcher-bot/cq-picsearcher-bot

      - name: 更新 Tsuk1ko/cq-picsearcher-bot 版本号
        id: checker
        run: |
          cd cq-picsearcher-bot
          if [ "${{ env.VERSION }}" ]; then
            echo "${{ env.VERSION }}" > ./version
          else
            echo "VERSION=$(cat ./version)" >> $GITHUB_ENV
          fi

      - name: Import GPG Key
        if: github.event_name != 'workflow_dispatch'
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache/cq-picsearcher-bot
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            silicer/cq-picsearcher-bot:latest
            silicer/cq-picsearcher-bot:${{ env.VERSION }}
          context: ./cq-picsearcher-bot
          platforms: linux/amd64, linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache/cq-picsearcher-bot
          cache-to: type=local,dest=/tmp/.buildx-cache/cq-picsearcher-bot-new,mode=max

      - name: Post build and push
        run: |
          rm -rf ./cq-picsearcher-bot/cq-picsearcher-bot
          rm -rf /tmp/.buildx-cache/cq-picsearcher-bot
          mv /tmp/.buildx-cache/cq-picsearcher-bot-new /tmp/.buildx-cache/cq-picsearcher-bot

      - name: commit
        if: github.event_name != 'workflow_dispatch'
        run: |
          git config --global user.email ${{ secrets.mail }}
          git config --global user.name ${{ secrets.username }}
          git add .
          tIme=$(env TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S")
          git commit -S -m "cq-picsearcher-bot built and updated at ${tIme} UTC+8" -a

      - name: Push changes
        if: github.event_name != 'workflow_dispatch'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
