name: ELF_RSS 镜像构建
on:
  repository_dispatch:
    types: [ELF_RSS]
  workflow_dispatch:

env:
  VERSION: ${{ github.event.client_payload.version }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone
        run: git clone https://github.com/Quan666/ELF_RSS ./ELF_RSS/ELF_RSS

      - name: 更新 Quan666/ELF_RSS 版本号
        id: checker
        run: |
          cd ELF_RSS
          awk '{ sub(/nonebot2/, "nonebot2[fastapi]"); print $0 }' ELF_RSS/requirements.txt | tee > ELF_RSS/requirements.txt
          cat ELF_RSS/requirements.txt
          if [ "${{ env.VERSION }}" ]; then
            echo "${{ env.VERSION }}" > ./version
          else
            echo "VERSION=$(cat ./version)" >> $GITHUB_ENV
          fi

      - name: Import GPG Key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action

      - name: Login to DockerHub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/ELF_RSS
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            silicer/elf_rss:latest
            silicer/elf_rss:${{ env. VERSION }}
          context: ./ELF_RSS
          cache-from: type=local,src=/tmp/.buildx-cache/ELF_RSS
          cache-to: type=local,dest=/tmp/.buildx-cache/ELF_RSS-new,mode=max

      - name: Post build and push
        run: |
          rm -rf ./ELF_RSS/ELF_RSS
          rm -rf /tmp/.buildx-cache/ELF_RSS
          mv /tmp/.buildx-cache/ELF_RSS-new /tmp/.buildx-cache/ELF_RSS

      - name: commit
        if: github.event_name != 'workflow_dispatch'
        run: |
          git config --global user.email ${{ secrets.mail }}
          git config --global user.name ${{ secrets.username }}
          git add .
          tIme=$(env TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S")
          git commit -S -m "ELF_RSS built and updated at ${tIme} UTC+8" -a

      - name: Push changes
        if: github.event_name != 'workflow_dispatch'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
