name: sagernet/v2ray 镜像构建
on:
  repository_dispatch:
    types: [v2ray]
  workflow_dispatch:

env:
  VERSION: ${{ github.event.client_payload.version }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: 更新版本号
        id: checker
        run: |
          if [ "${{ env.VERSION }}" ]; then
            echo ${{ env.VERSION }} > sagernet-v2ray-core/version
          else
            echo "VERSION=$(cat sagernet-v2ray-core/version)" >> $GITHUB_ENV
          fi


      - name: Download latest x64 sagernet/v2ray release
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        run: |
          cd sagernet-v2ray-core
          curl -sSL -O https://github.com/SagerNet/v2ray-core/releases/download/${{ env.VERSION }}/v2ray-linux-64.zip
          curl -sSL -O https://github.com/SagerNet/v2ray-core/releases/download/${{ env.VERSION }}/v2ray-linux-arm64-v8a.zip
          unzip v2ray-linux-64.zip -d amd64 && rm v2ray-linux-64.zip
          unzip v2ray-linux-arm64-v8a.zip -d arm64 && rm v2ray-linux-arm64-v8a.zip

      - name: Import GPG Key
        if: github.event_name != 'workflow_dispatch'
        id: import_gpg
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            silicer/v2ray-core
          tags: |
            type=raw,value=latest
            type=raw,value=${{ env.VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up cache
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/sagernet-v2ray-core
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v2
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        with:
          push: true
          context: ./sagernet-v2ray-core
          platforms: linux/amd64, linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache/sagernet-v2ray-core
          cache-to: type=local,dest=/tmp/.buildx-cache/sagernet-v2ray-core-new,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Post build and push
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        run: |
          rm -rf sagernet-v2ray-core/a*
          rm -rf /tmp/.buildx-cache/sagernet-v2ray-core
          mv /tmp/.buildx-cache/sagernet-v2ray-core-new /tmp/.buildx-cache/sagernet-v2ray-core

      - name: commit
        if: github.event_name != 'workflow_dispatch'
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        run: |
          git config --global user.email ${{ secrets.mail }}
          git config --global user.name ${{ secrets.username }}
          git add .
          tIme=$(env TZ=Asia/Shanghai date "+%Y-%m-%d %H:%M:%S")
          git commit -S -m "sagernet-v2ray-core built and updated at ${tIme} UTC+8" -a

      - name: Push changes
        if: github.event_name != 'workflow_dispatch'
        # if: ${{ steps.checker.outputs.ifUpdated == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
